apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  CONNECTION_STRING: "Host=pgbooking133.postgres.database.azure.com;Port=5432;Database=bookingdb;Username=pgadmin@pgbooking133;Password=StrongP@ssw0rd123!;SSL Mode=Require;Trust Server Certificate=true;"