apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DATABASE_URL: "postgres://pgadmin:StrongP%40ssw0rd123!@pgbooking133.postgres.database.azure.com:5432/bookingdb?sslmode=require"
